[project]
name = "flask-app-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-scss>=0.5",
    "flask-sqlalchemy>=3.1.1",
]
